import { Page, View, Text } from '@react-pdf/renderer';
import type { ReportData } from '../types/reportData';
import type { ReportTheme } from '../types/theme';
import { createStyles } from '../styles/createStyles';
import { LABELS } from '../types/reportData';
import PageHeader from '../shared/PageHeader';
import PageFooter from '../shared/PageFooter';
import SectionTitle from '../shared/SectionTitle';
import { formatReportDate } from '../utils/dateFormatter';

interface DisclaimerPageProps {
  data: ReportData;
  theme: ReportTheme;
}

export default function DisclaimerPage({ data, theme }: DisclaimerPageProps) {
  const s = createStyles(theme);
  const { metadata } = data;
  const labels = LABELS[metadata.language];

  return (
    <Page size="A4" style={s.page}>
      <PageHeader title={labels.disclaimer} theme={theme} />

      <SectionTitle watermark="LEGAL" title={labels.disclaimer} theme={theme} />

      <View style={{ marginBottom: 20 }}>
        <Text style={s.bodyText}>
          This report was generated by the ClearGate automated screening platform on {formatReportDate(metadata.generated_at)}.
        </Text>
      </View>

      <View style={{ marginBottom: 16 }}>
        <Text style={s.subsectionTitle}>Important Notice</Text>
        <Text style={s.bodyText}>
          This intelligence report is provided for informational purposes only and does not constitute legal, financial, or compliance advice. The information contained herein has been compiled from publicly available sources and proprietary databases. While every effort has been made to ensure accuracy, ClearGate makes no representation or warranty, express or implied, as to the completeness, accuracy, or reliability of the information.
        </Text>
      </View>

      <View style={{ marginBottom: 16 }}>
        <Text style={s.subsectionTitle}>Confidentiality</Text>
        <Text style={s.bodyText}>
          This report is classified as {metadata.classification} and is intended solely for the use of the individual or entity to whom it is addressed. Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, please contact ClearGate immediately and destroy all copies of this report.
        </Text>
      </View>

      <View style={{ marginBottom: 16 }}>
        <Text style={s.subsectionTitle}>AI-Generated Content</Text>
        <Text style={s.bodyText}>
          Sections of this report marked as AI-generated have been produced using artificial intelligence models. AI-generated content should be treated as preliminary analysis and must be reviewed by a qualified compliance professional before making any decisions based on its conclusions.
        </Text>
      </View>

      <View style={{ marginBottom: 16 }}>
        <Text style={s.subsectionTitle}>Data Currency</Text>
        <Text style={s.bodyText}>
          The data in this report reflects the state of source databases at the time of generation. Sanctions lists, PEP databases, and adverse media sources are updated continuously. Users should verify critical findings against the most current source data before relying on them for compliance decisions.
        </Text>
      </View>

      <View style={s.spacerXl} />

      {/* Report metadata */}
      <View style={[s.card, { backgroundColor: theme.colors.backgroundAlt }]}>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
          <View style={{ width: '50%', marginBottom: 6 }}>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 7, color: theme.colors.textLight }}>Report ID</Text>
            <Text style={{ fontFamily: theme.fonts.mono, fontSize: 8, color: theme.colors.text }}>{metadata.report_id}</Text>
          </View>
          <View style={{ width: '50%', marginBottom: 6 }}>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 7, color: theme.colors.textLight }}>Generated</Text>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 8, color: theme.colors.text }}>{formatReportDate(metadata.generated_at)}</Text>
          </View>
          <View style={{ width: '50%', marginBottom: 6 }}>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 7, color: theme.colors.textLight }}>Classification</Text>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 8, color: theme.colors.text }}>{metadata.classification}</Text>
          </View>
          <View style={{ width: '50%', marginBottom: 6 }}>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 7, color: theme.colors.textLight }}>Platform</Text>
            <Text style={{ fontFamily: theme.fonts.body, fontSize: 8, color: theme.colors.text }}>{metadata.generated_by}</Text>
          </View>
        </View>
      </View>

      <PageFooter classification={metadata.classification} theme={theme} />
    </Page>
  );
}
